before_commands:
    - composer install
tools:
    php_code_sniffer:
        enabled: true
        extensions:
            - php
        command: phpcs
        filter:
            paths: [src/*]
            excluded_paths: ["*/Tests/*"]
        config:
            standard: PSR2
            sniffs: []
            severity: ~
            error_severity: ~
            warning_severity: ~
            tab_width: ~
            encoding: UTF-8
    php_analyzer:
        enabled: true
        filter:
            paths: [src/*]
            excluded_paths: ["*/Tests/*"]
    php_code_coverage:
        enabled: true
        config_path: ~
        test_command: phpunit
        only_changesets: false
        filter:
            paths: [src/*]
            excluded_paths: ["*/Tests/*"]
    php_cs_fixer: false
    php_mess_detector: false
    php_cpd: false
