language: php

php:
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_script:
    - composer install --prefer-source --no-interaction --dev

script:
    - mkdir -p build/logs
    - phpunit

after_script:
    - php vendor/bin/coveralls
